language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgeos-dev
  - pip install pipenv

install:
  - pipenv install --skip-lock

script:
  - python setup.py test