language: python
python:
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgeos-dev python3-tk
  - pip install pipenv

install:
  - pipenv install --dev --skip-lock

script:
  - python ./tests/test.py